kind: Service
apiVersion: v1
metadata:
  name: frontend-app
spec:
  selector:
    app: frontend-app
  ports:
  - protocol: TCP
    port: 8081
    nodePort: 30001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  selector:
      matchLabels:
        app: frontend-app
  replicas: 3
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-app
          image: shinyay/minikube-front-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
